-------------------------------------------------------------------------------------
-- Trigger to ensure only admin users can be assigned as station admins -------------
CREATE OR REPLACE FUNCTION check_admin_station()
RETURNS TRIGGER AS $$
DECLARE
    user_type VARCHAR(20);
BEGIN
    -- Obtener tipo de usuario
    SELECT u_type INTO user_type
    FROM user
    WHERE id = NEW.admin_id;

    -- Si no es admin, bloquear inserción
    IF user_type <> 'admin' THEN
        RAISE EXCEPTION 'Only admin users can be assigned as station admins.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- creation of da trigger
CREATE TRIGGER trg_check_admin_station
BEFORE INSERT ON station
FOR EACH ROW
EXECUTE FUNCTION check_admin_station();
-------------------------------------------------------------------------------------
-- Trigger to prevent insertion of measurements with future dates -------------------
CREATE OR REPLACE FUNCTION prevent_future_measurements()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.m_date > NOW() THEN
        RAISE EXCEPTION 'Measurement date cannot be in the future.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- creation of da trigger
CREATE TRIGGER trg_prevent_future_measurements
BEFORE INSERT ON measurement
FOR EACH ROW
EXECUTE FUNCTION prevent_future_measurements();
-------------------------------------------------------------------------------------
-- Trigger to update sensor's installment_date when its state changes to 'mantenimiento'
CREATE OR REPLACE FUNCTION update_maintenance_date()
RETURNS TRIGGER AS $$
BEGIN
    -- Solo actualizar cuando cambie a 'mantenimiento'
    IF NEW.s_state = 'mantenimiento' AND OLD.s_state <> 'mantenimiento' THEN
        NEW.last_calibration_date = NOW();
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- creation of da trigger
CREATE TRIGGER trg_update_maintenance_date
BEFORE UPDATE ON sensor
FOR EACH ROW
EXECUTE FUNCTION update_maintenance_date();
-------------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION log_report_creation()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO report_log (report_id, institution_id, description)
    VALUES (NEW.report_id, NEW.institution_id, 'Report generated by institution');

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
--- creation of da trigger
CREATE TRIGGER trg_log_report_creation
AFTER INSERT ON report
FOR EACH ROW
EXECUTE FUNCTION log_report_creation();
-------------------------------------------------------------------------------------