# Generated by Django 6.0 on 2025-12-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='lat',
            field=models.CharField(max_length=32, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='station',
            name='lon',
            field=models.CharField(max_length=32, verbose_name='Longitud'),
        ),
    ]
