# Generated by Django 6.0 on 2025-12-06 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_initial'),
        ('stations', '0004_station_connection_request_fields'),
        ('users', '0005_remove_email_id_remove_phonenumber_id_email_email_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationrequest',
            name='institution',
            field=models.ForeignKey(db_column='institution_id', on_delete=django.db.models.deletion.CASCADE, to='institutions.institution', verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='stationrequest',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='stationrequest',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='stationrequest',
            name='submitted_by',
            field=models.ForeignKey(db_column='submitted_by', on_delete=django.db.models.deletion.CASCADE, related_name='station_requests', to='users.user', verbose_name='Solicitado por'),
        ),
    ]
