# Generated by Django 5.2.8 on 2025-11-26 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('u_password', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('u_type', models.CharField(max_length=20)),
                ('validated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_number', models.CharField(max_length=15, unique=True)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='users.user')),
            ],
        ),
    ]
