# Generated by Django 5.2.8 on 2025-11-26 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='email',
            table='email',
        ),
        migrations.AlterModelTable(
            name='phonenumber',
            table='phone_number',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
