# Generated by Django 5.2.8 on 2025-12-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_align_fk_columns_to_u_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={},
        ),
        migrations.AlterModelOptions(
            name='phonenumber',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
