# Generated by Django 5.2.8 on 2025-12-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_email_options_alter_phonenumber_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='id',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='id',
        ),
        migrations.AddField(
            model_name='email',
            name='email_id',
            field=models.AutoField(db_column='email_id', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='p_number_id',
            field=models.AutoField(db_column='p_number_id', primary_key=True, serialize=False),
        ),
    ]
